### ISSUE TITLE
Operationalize/Finalize PDG Viz Workflow on Kubernetes

### ISSUE THREAD

**Issue by alonakos** [PermafrostDiscoveryGateway/viz-workflow#48]
This ticket aims to make the PDG Viz Workflow fully operational on Kubernetes (K8s). Deploying on K8s will allow for greater scalability across different clusters, and converting the workflow into a service will enable team members to independently trigger and manage various stages, moving away from the current manual process.

### Description

The goal is to make the entire Viz Workflow deployable on K8s. Related issue: [Viz Workflow #1(https://github.com/PermafrostDiscoveryGateway/viz-workflow/issues/1)

**Subtasks and Dependencies**: Certain issues are prerequisite tasks for the above.

[Issue #33](https://github.com/PermafrostDiscoveryGateway/viz-workflow/issues/33), [Issue #46](https://github.com/PermafrostDiscoveryGateway/viz-workflow/issues/46)

**Modularize Configuration**: The workflow uses a single configuration file. We need separate configurations for each stage to deploy stages independently.

- [ ] Check with @Rushiraj to synch the work and ensure we are aligned.

**Complete Processing of the Ice Wedge Polygon Dataset:** Related Issue: [PDG-Portal #24](https://github.com/PermafrostDiscoveryGateway/pdg-portal/issues/24)

- [ ] Review comments in Issue #24 for insights on workflow optimization related to dataset deduplication and overlap.

**Additional requirements:** WMTS Capabilities Document: Update viz-raster to generate WMTS capabilities documents for subset downloads.

### TODO

- [ ] Check in with @Rushiraj about the API design document.
- [ ] Start by testing the setup with a simple dataset before moving to the IWP dataset.

**Comment by rushirajnenuji** [comment]
This is sort of completed. We already have the support for viz-workflow, and recently added support for Parallel interface for shell recipes. Currently WIP testing of [Chunli Dai's Elevation change dataset](https://github.com/PermafrostDiscoveryGateway/pdg-portal/issues/21), which involves running it on dev/staging environment. I'll link the latest release and close this out once @alonakos and I are done with testing.
